#sifat-sifat determinant
1. Apabila semua elemen dari salah satu baris atau kolom sama dengan nol, maka determinan matriks tersebut adalah nol.
2. merubah baris akan merubah determinant dari sebuah matrik
3. determinat  menggunakan libary numpy untuk menghitung semua matrix dari A sampai G determinant adalah nilai yang di peroleh dalam perkalian entri-entri tertentu pada matriks yang memenuhi kofaktor tertentu.

# experimen
1.

In [ ]:
import numpy as np
A = np. array (([1,0],[0,1]))
B = np.array (([1,0,0],[0,1,0],[0,0,1]))
c = np.array (([1,2,1],[3,1,2],[2,1,2]))
D = np.array (([3,1,2],[1,2,1],[2,1,2]))
E = np.array (([1,2,1],[2,4,2],[2,1,2]))
F = np.array (([1,2,1],[2,4,2],[2,4,3]))
G = np.array (([6,2,4],[2,4,2],[4,2,3]))
H = np.array (([6,8],[4,2]))
I = np.array (([6,8],[2,1]))
J = np.array (([6,4],[4,1]))


det_A=np.linalg.det(A)
det_B=np.linalg.det(B)
det_C=np.linalg.det(c)
det_D=np.linalg.det(D)
det_E=np.linalg.det(E)
det_F=np.linalg.det(F)
det_G=np.linalg.det(G)
det_H=np.linalg.det(H)
det_I=np.linalg.det(I)
det_J=np.linalg.det(J)


print(det_A)
print(det_B)
print(det_C)
print(det_D)
print(det_E)
print(det_F)
print(det_G)
print(det_H)
print(det_I)
print(det_J)


- ketika ada Matriks A dan B dengan ordo yang sama, matriks B Merupakan kelipatan dari matriks A dan determinan dari matriks A sudah diketahui maka determinan B = Kelipatan dari elemen matriks dikali hasil determinan matriks A.
contoh: $2^{3}$.3

In [ ]:

import numpy as np
D= np.array([[3,1,2],[1,2,1],[2,1,2]])
g= np.array([[6,2,4],[2,4,2],[4,2,4]])
print(D)
D=np.linalg.det(D)
print(f'Determinannya:',{D})
print()
print(g)
g=np.linalg.det(g)
print(f'Determinannya:',{g})

[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinannya: {3.000000000000001}

[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinannya: {24.000000000000014}


In [ ]:
#Mtriks Segitiga atas
import numpy as np
k= np.array([[1,2,3],[0,2,1],[0,0,1]])
print(k)
k=np.linalg.det(k)
print(f'Determinannya:',{k})

[[1 2 3]
 [0 2 1]
 [0 0 1]]
Determinannya: {2.0}


In [ ]:
l= np.array([[1,0,0],[2,1,0],[4,1,3]])
print(l)
l=np.linalg.det(l)
print(f'Determinannya:',{l})

[[1 0 0]
 [2 1 0]
 [4 1 3]]
Determinannya: {2.9999999999999996}


Determinan matriks C= det(AB)

In [ ]:
import numpy as np
a= np.array([[2,1],[1,1]])
print(a)
a=np.linalg.det(a)
print(f'Determinannya:',{a})
print()
b= np.array([[1,1],[1,1]])
print(b)
b=np.linalg.det(b)
print(f'Determinannya:',{b})

In [ ]:
C=np.array([[3,3],[2,2]])
print(C)
C=np.linalg.det(C)
print(f'Determinannya:',{C})

In [ ]:
import numpy as np

a = np.array([[3,1,3],[2,1,2],[4,2,1]])

inverse_matrix = np.linalg.inv(a)

print("Matriks:")
print(a)
print("\nInvers Matriks:")
print(inverse_matrix)

Matriks:
[[3 1 3]
 [2 1 2]
 [4 2 1]]

Invers Matriks:
[[ 1.         -1.66666667  0.33333333]
 [-2.          3.         -0.        ]
 [ 0.          0.66666667 -0.33333333]]


menghitung 5x5 faktor determinant matrik

## menghitung derterminant matrik dan ivers matrik
menggunakan matrik 5x5


rumus  $z^{-1}$ = 1/det matriks.$z^{T}$

z= $\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   2&3&3&4&2\\
    2& 3& 4&1&3\\
    1& 3 & 4&1&3\\
    2&3&4&1&2\\
    2&3&4&5&2 \end{array}\right]
\end{equation}
\end{split}$

In [1]:
import numpy as np
z= np.array([[2,3,3,4,2],[2,3,4,1,3],[1,4,3,4,3],[2,3,4,1,2],[2,3,4,5,2]])
print(z)
print()
x=np.transpose(z)
print(x)

[[2 3 3 4 2]
 [2 3 4 1 3]
 [1 4 3 4 3]
 [2 3 4 1 2]
 [2 3 4 5 2]]

[[2 2 1 2 2]
 [3 3 4 3 3]
 [3 4 3 4 4]
 [4 1 4 1 5]
 [2 3 3 2 2]]


In [2]:
v=np.linalg.det(z)
print(f"determinan:",{v})
v=round(v)
print(v)

determinan: {-20.000000000000007}
-20


In [3]:
k=v/1
print(k)

-20.0


In [4]:
L=k*x
print(L)

[[ -40.  -40.  -20.  -40.  -40.]
 [ -60.  -60.  -80.  -60.  -60.]
 [ -60.  -80.  -60.  -80.  -80.]
 [ -80.  -20.  -80.  -20. -100.]
 [ -40.  -60.  -60.  -40.  -40.]]
