# Matrix Invers

* sifat-sifat matrix invers

* mencari invers dengan eliminasi gaus jordan

* solusi sistem persamaan linier dengan matrix invers

* (membuat soal persamaan linier 6 variabel)

## Matrix Invers

Dalam aljabar linear matrix persegi A n x n disebut invertible (atau juga disebut nonsingular, nondegenerate, atau biasanya digunakan secara umum).

Jika terdapat sebuah matrix persegi B n x n maka: AB = BA = I, dimana I adalah dinotasikan dengan matrix Identitas n x n dan perkalian yang digunakan adalah perkalian matrix biasa. Maka Matrix B secara unik ditentukan oleh Matrix A, dan disebut Inverse dari Matrix A. dinotasikan dengan

. Matrix inversion adalah proses untuk menemukan invers marix dari invertible Matrix. Lain halnya Matrix persegi yang tidak dapat dibalik disebut Matrix singular atau matrix tunggal atau degenerate

## Sifat sifat Matrix Invers

Matrix invers adalah sifat yang berlaku pada matrix yang merupakan kebalikan dari Matrix asal. Matrix invers dapat ditulis dengan simbol yang berarti jika dikalikan dengan Matrix A akan menghasilkan Matrix Identitas atau Matrix. Matrix Identitas adalah Matrix yang memiliki angka 1 sebagai diagonal utamanya dan selain itu angka 0 nilainya.

**Berikut adalah sifat sifat Matrix Invers:**

1. Matrix Invers hanya dimiliki oleh Matrix persegi atau Matrix yang memiliki baris dan kolom yang sama

2. Matrix invers hanya ada pada Matrix yang non-singular, yaitu Determinannya tidak sama dengan 0

3. Invers Matrix bersifat tunggal, artinya tidak ada matrix invers selain yang menjadi invers dari matrix tersebut. Jika B dan C adalah invers dari Matrix A, maka B = C.

4. Invers dari invers suatu Matrix adalah Matrix itu sendiri

5. Invers dari hasil kali dua atau lebih matriks adalah hasil kali invers-inversnya dalam urutan terbalik. Jika A dan B keduanya nonsingular, maka (AB)^-1 = B^-1 A^-1.

untuk mencari invers matriks dengan metode eliminasi gauss jordan caranya sebagai berikut:
contoh matriks A
     \begin{bmatrix}
    1 &-2&-1\\
    -1& 2& 0\\
    1& -3 & 1
    \end{bmatrix}
    pertama-tama kita anggap baris pertama pada matriks diatas itu B1, baris kedua itu B2 dan baris ketiga itu B3
    kemudian kita tulis matriks A dan identitas matriks A disebelah matriks A=
     \begin{bmatrix}
    1 &-2&-1|1 & 0 & 0\\
    -1& 2& 0|0 & 1&0\\
    1& -3 & 1|0&0&1
    \end{bmatrix}
    setelah itu ubahlah matriks A menjadi matriks identitas

#mencari invers dengan eliminasi gauss jordan

di sini saya akan mencari  ivers eliminasi gauss jordan

menurut gauss jordan :

(A|I)(A-1)

Di mana A = Matriks

I         = Matriks identitas

A-1       =  Invers Matriks

misalnya kita mau mencari invers dari sebuah matriks dengan ordo 3x3
contoh :

A
 \begin{bmatrix}
    1 &2& 3\\
    0& 1& 4\\
    5& 6 & 0
    \end{bmatrix}

I
 \begin{bmatrix}
    1 &0& 0\\
    0& 1& 0\\
    0& 0 & 1
    \end{bmatrix}
setelah itu kita gunakan eliminasi geuss jordan
 \begin{bmatrix}
    1 &2& 3|1&0&0\\
    0& 1& 4|0&1&0\\
    5& 6 & 0|0&0&1
    \end{bmatrix}
untuk mencari invers,caranya matriks identitasnya bisa ada disebelah kiri, terserah baris berapa mau di tambahin/dikurangin/dikali/dibagi sama baris keberapa.penyelesaiannya:

sekarang kurangkan baris ketiga dengan 5x baris pertama, maksud dari baris pertama dikalikan 5 dulu baru abis itu buat ngurangin baris ke tiga hasilnya :
 \begin{bmatrix}
    1 &2& 3|1&0&0\\
    0& 1& 4|0&1&0\\
    0& -4& -15|-5&0&1
    \end{bmatrix}
dari matriks diatas,tambahkan baris ke tiga dengan 4 kali baris kedua. hasilnya :
\begin{bmatrix}
    1 &2& 3|1&0&0\\
    0& 1& 4|0&1&0\\
    0& 0& 1|5&4&1
    \end{bmatrix}
selanjutnya kurangkan baris kedua dengan 4x baris ketiga.
dan kita kurangkan juga baris pertama dengan 3x baris ketiga. hasilnya:
\begin{bmatrix}
    1 &2& 0|16&-12&-3\\
    0& 1& 0|20&-15&-4\\
    0& 0& 1|-5&4&1
    \end{bmatrix}
langkah terakhir tinggal kurangkan baris pertama dengan 2x baris kedua.hasilnya :
\begin{bmatrix}
    1 &0& 0|-24&18&5\\
    0& 1& 0|20&-15&-4\\
    0& 0& 1|-5&4&1
    \end{bmatrix}
yang ada disebelah kanan adalah invers dari matrik A.
jadi invers matriknya:

A-1
\begin{bmatrix}
    -24&18&5\\
    20&-15&-4\\
    -5&4&1
    \end{bmatrix}


Dalam penerapan gauss Jordan dengan menggunakan Operasi Baris Elementer atau disebut OBE. Operai OBE terdiri dari 3 cara, yaitu:
1. Menambahkan kelipatan baris ke baris yang lain (RowAdd)
2. mengkalikan baris dengan bilangan selain nol (RowScale)
3. Menukarkan posisi baris satu dengan baris yang lain (RowSwap)

Untuk mencari Invers dari sebuah Matrix kita harus memperhatikan persamaan - persamaannya. Untuk bisa memasukkannya dalam bentuk matrix kita pisah antara koefisien yang ada disebelah ruas kiri dan konstanta yang ada disebelah ruas kanan.
contoh saya mempunyai persamaan linier 6 variabel:


$
\begin{align*}
KoefisienA=
\begin{bmatrix}
1&3&4&2&3&1\\
1&2&3&4&3&2\\
2&1&1&5&2&3\\
2&4&3&1&5&3\\
2&4&4&3&5&1\\
1&3&4&3&2&4
\end{bmatrix}
\end{align*}
$
$
\begin{align*}
I=
\begin{bmatrix}
1&0&0&0&0&0\\
0&1&0&0&0&0\\
0&0&1&0&0&0\\
0&0&0&1&0&0\\
0&0&0&0&1&0\\
0&0&0&0&0&1
\end{bmatrix}
\end{align*}
$

## Solusi sistem persamaan linier dengan matrix invers dengan 6 variabel

Untuk bisa kita menemukan invers dari suatu matrix, kita harus melakukan operasi - operasi baris elementer pada Matrix Identitas yang dimana operasi operasi baris elemternya sama dengan operasi - operasi baris elementer yang mengubah Matrix KoefisienA menjadi matrix identitas.

## Penyelesaian dengan code

Berikut adalah contoh penyelesaian mencari Invers Matrix 6x6 dengan code python

In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
# Import library numpy and memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[2,2,2,4,3,6,25],[2,2,1,4,4,5,22],[1,1,3,4,1,6,23],[3,2,1,1,2,3,16],[2,1,2,3,1,3,17],[1,2,1,1,3,1,13]])
print(f"Matrix A  = \n{A}")
print("\n")
B  = np.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])
print(f"Matrix I = \n{B}")

Matrix A  = 
[[ 2  2  2  4  3  6 25]
 [ 2  2  1  4  4  5 22]
 [ 1  1  3  4  1  6 23]
 [ 3  2  1  1  2  3 16]
 [ 2  1  2  3  1  3 17]
 [ 1  2  1  1  3  1 13]]


Matrix I = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
A1 = RowSwap(A,0,2)
print(A1)
print("\n")

B1 = RowSwap(B,0,2)
print(B1)
print("\n")

A2 = RowAdd(A1,0,1,-2)
print(A2)
print("\n")

B2 = RowAdd(B1,0,1,-2)
print(B2)
print("\n")

A3 = RowAdd(A2,0,2,-2)
print(A3)
print("\n")

B3 = RowAdd(B2,0,2,-2)
print(B3)
print("\n")

A4 = RowAdd(A3,0,3,-3)
print(A4)
print("\n")

B4 = RowAdd(B3,0,3,-3)
print(B4)
print("\n")

A5 = RowAdd(A4,0,4,-2)
print(A5)
print("\n")

B5 = RowAdd(B4,0,4,-2)
print(B5)
print("\n")

A6 = RowAdd(A5,0,5,-1)
print(A6)
print("\n")

B6 = RowAdd(B5,0,5,-1)
print(B6)

[[ 1.  1.  3.  4.  1.  6. 23.]
 [ 2.  2.  1.  4.  4.  5. 22.]
 [ 2.  2.  2.  4.  3.  6. 25.]
 [ 3.  2.  1.  1.  2.  3. 16.]
 [ 2.  1.  2.  3.  1.  3. 17.]
 [ 1.  2.  1.  1.  3.  1. 13.]]


[[0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


[[  1.   1.   3.   4.   1.   6.  23.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]
 [  2.   2.   2.   4.   3.   6.  25.]
 [  3.   2.   1.   1.   2.   3.  16.]
 [  2.   1.   2.   3.   1.   3.  17.]
 [  1.   2.   1.   1.   3.   1.  13.]]


[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  1. -2.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


[[  1.   1.   3.   4.   1.   6.  23.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  3.   2.   1.   1.   2.   3.  16.]
 [  2.   1.   2.   3.   1.   3.  17.]
 [  1.   2.   1.   1.   3.   1.  13.]]


[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  1. -2.  0.  0.  0.]
 

In [ ]:
A7 = RowSwap(A6,5,1)
print(A7)
print("\n")

B7 = RowSwap(B6,5,1)
print(B7)
print("\n")

A8 = RowAdd(A7,1,0,-1)
print(A8)
print("\n")

B8 = RowAdd(B7,1,0,-1)
print(B8)
print("\n")

A9 = RowAdd(A8,1,3,1)
print(A9)
print("\n")

B9 = RowAdd(B8,1,3,1)
print(B9)
print("\n")

A10 = RowAdd(A9,1,4,1)
print(A10)
print("\n")

B10 = RowAdd(B9,1,4,1)
print(B10)
print("\n")

[[  1.   1.   3.   4.   1.   6.  23.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  0.  -1.  -8. -11.  -1. -15. -53.]
 [  0.  -1.  -4.  -5.  -1.  -9. -29.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1.  0. -2.  0.  0.  0.]
 [ 0.  0. -3.  1.  0.  0.]
 [ 0.  0. -2.  0.  1.  0.]
 [ 0.  1. -2.  0.  0.  0.]]


[[  1.   0.   5.   7.  -1.  11.  33.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  0.  -1.  -8. -11.  -1. -15. -53.]
 [  0.  -1.  -4.  -5.  -1.  -9. -29.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[ 0.  0.  2.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1.  0. -2.  0.  0.  0.]
 [ 0.  0. -3.  1.  0.  0.]
 [ 0.  0. -2.  0.  1.  0.]
 [ 0.  1. -2.  0.  0.  0.]]


[[  1.   0.   5.   7.  -1.  11.  33.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  0.   0. -10. -14.   1. -20. -63.]
 [  0.  -1.  -4.  -5.  -1.  -9. -29.]
 [  0.   0.  -5.  

In [ ]:
A11 = RowAdd(A10,5,2,-1)
print(A11)
print("\n")

B11 = RowAdd(B10,5,2,-1)
print(B11)
print("\n")

A12 = RowAdd(A11,2,0,-5)
print(A12)
print("\n")

B12 = RowAdd(B11,2,0,-5)
print(B12)
print("\n")

A13 = RowAdd(A12,2,1,2)
print(A13)
print("\n")

B13 = RowAdd(B12,2,1,2)
print(B13)
print("\n")

A14 = RowAdd(A13,2,3,10)
print(A14)
print("\n")

B14 = RowAdd(B13,2,3,10)
print(B14)
print("\n")

A15 = RowAdd(A14,2,4,6)
print(A14)
print("\n")

B15 = RowAdd(B14,2,4,6)
print(B14)
print("\n")

A16 = RowAdd(A15,2,5,5)
print(A16)
print("\n")

B16 = RowAdd(B15,2,5,5)
print(B16)
print("\n")

[[  1.   0.   5.   7.  -1.  11.  33.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0. -10. -14.   1. -20. -63.]
 [  0.   0.  -6.  -8.   1. -14. -39.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[ 0.  0.  2.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [ 0.  0. -4.  1.  0.  1.]
 [ 0.  0. -3.  0.  1.  1.]
 [ 0.  1. -2.  0.  0.  0.]]


[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0. -10. -14.   1. -20. -63.]
 [  0.   0.  -6.  -8.   1. -14. -39.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[-5.  5.  2.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [ 0.  0. -4.  1.  0.  1.]
 [ 0.  0. -3.  0.  1.  1.]
 [ 0.  1. -2.  0.  0.  0.]]


[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0.  -3.   0.  -3.  -4.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0. -10. -14.   1. -20. -63.]
 [  0.   0.  -6.  -8.   1. -14. -39.]
 [  0.   0.  -5.  

[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0.  -3.   0.  -3.  -4.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0.   0.  -6.  -4.  -2. -12.]
 [  0.   0.   0.  -8.  -5.  -8. -21.]
 [  0.   0.   0.  -4.  -3.  -2.  -9.]]


[[-5.  5.  2.  0.  0. -1.]
 [ 2. -2. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [ 4. -4. -1.  1. -1.  0.]
 [ 6. -6. -3.  0.  1.  1.]
 [ 5. -4. -2.  0.  0.  0.]]


[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0.  -3.   0.  -3.  -4.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0.   0.   2.   2.   2.   6.]
 [  0.   0.   0.  -8.  -5.  -8. -21.]
 [  0.   0.   0.  -4.  -3.  -2.  -9.]]


[[-5.  5.  2.  0.  0. -1.]
 [ 2. -2. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [-6.  4.  3.  1. -1.  0.]
 [ 6. -6. -3.  0.  1.  1.]
 [ 5. -4. -2.  0.  0.  0.]]


[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0.  -3.   0.  -3.  -4.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0.   0.   1.   1.   1.   3.]
 [  0.   0.   0.  -8.  -5.  -8. -21.]
 [  0.   0.   0.  

[[ 1.  0.  0.  0. -3. -1. -3.]
 [ 0.  1.  0.  0.  3.  0.  5.]
 [ 0.  0.  1.  0. -1.  1.  3.]
 [ 0.  0.  0.  1.  1.  1.  3.]
 [ 0.  0.  0.  0.  1.  2.  3.]
 [ 0.  0.  0.  0.  3.  0.  3.]]


[[ 16.   -9.   -8.5  -3.5   3.5  -1. ]
 [ -7.    4.    3.5   1.5  -1.5   1. ]
 [  1.   -1.    0.    0.    0.    0. ]
 [ -3.    2.    1.5   0.5  -0.5   0. ]
 [ -7.    4.    4.    2.   -2.    0. ]
 [-18.   10.    9.    4.   -3.    1. ]]


[[ 1.  0.  0.  0.  0.  5.  6.]
 [ 0.  1.  0.  0.  3.  0.  5.]
 [ 0.  0.  1.  0. -1.  1.  3.]
 [ 0.  0.  0.  1.  1.  1.  3.]
 [ 0.  0.  0.  0.  1.  2.  3.]
 [ 0.  0.  0.  0.  3.  0.  3.]]


[[ -5.    3.    3.5   2.5  -2.5  -1. ]
 [ -7.    4.    3.5   1.5  -1.5   1. ]
 [  1.   -1.    0.    0.    0.    0. ]
 [ -3.    2.    1.5   0.5  -0.5   0. ]
 [ -7.    4.    4.    2.   -2.    0. ]
 [-18.   10.    9.    4.   -3.    1. ]]


[[ 1.  0.  0.  0.  0.  5.  6.]
 [ 0.  1.  0.  0.  0. -6. -4.]
 [ 0.  0.  1.  0. -1.  1.  3.]
 [ 0.  0.  0.  1.  1.  1.  3.]
 [ 0.  0.  0.  0.  1.  2

In [4]:


import numpy as np
A=np.array([[8,9],[1,2]])
print(A)

b = np.array([[2,2],[1,2]])
print(b)
print(A+b)

[[8 9]
 [1 2]]
[[2 2]
 [1 2]]
[[10 11]
 [ 2  4]]
